[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["Atri Hegde <iamatrihegde@outlook.com>"]
license = "GPL-v3"
description = "CLI sudoku solver"
readme = "README.org"
edition = "2021"

[dependencies]
